### ISSUE TITLE
Verify that release documentation is sufficient

### ISSUE THREAD

**Issue by selfissued** [openid-certification/oidctest#120]
We agreed to have @panva do a release based on updated documentation that @zandbelt is creating.  The current plan is for #75 to be addressed and then for the release to be done.

**Comment by zandbelt** [comment]
FWIW: I'm pretty sure the doc is insufficient at this point to do a full release without any help from me. But I wanted to sit down with @panva and go over the doc to fill out the blanks based on factual demand rather than guesses from my side. But let's just plan this in the next weeks and see how far we get.

**Comment by zandbelt** [comment]
the pre-req #75 is done now and part of the master branch; we can now go ahead an plan a new (minor) release; @panva let's agree on a date for that

**Comment by zandbelt** [comment]
TODOs:
- make `openid-certification/oidctest` and `openid-certification/otest` the "masters" instead of them being forks from the corresponding `rohe` repositories; this should make the flow of patches upstream simpler, which usually would start at an issue in `openid-certification/oidctest` anyhow

**Comment by zandbelt** [comment]
we managed to release 2.1.5 and RP 1.1.4 today, just need to finish up loose ends on the documentation and process https://github.com/openid-certification/oidctest/releases/tag/v1.1.6

**Comment by selfissued** [comment]
Congratulations @zandbelt and @panva on getting this done!

**Comment by zandbelt** [comment]
The loose ends are fixed in:
https://github.com/openid-certification/oidctest/commit/21375734c755968da452089c8f2a91eaefddcda4
and the updated release management document (version 2.1.0) is available on the master branch 
https://github.com/openid-certification/oidctest/blob/master/docs/maintenance.md#release-management
