### ISSUE TITLE
Test OP-IDToken-C-Signature uses "client_secret_basic" even though "client_secret_post" has been specified in configuration

### ISSUE THREAD

**Issue by prasannaramachandran** [openid-certification/oidctest#142]
Our /token endpoint only supports client_secret_post to pass in clientID and clientSecret. I have set up the configuration tool accordingly - 
https://op.certification.openid.net:60000/action/update?iss=https%3A%2F%2Fapi.stg-myteksi.com%2Fgrabid%2Fv1%2Foauth2&tag=GrabId+Staging+Basic

But the test "OP-IDToken-C-Signature" still uses client_secret_basic (which we don't support)

**Comment by selfissued** [comment]
Mike will look for the spec text on client_secret_basic and cite it in the issue.

**Comment by travisspencer** [comment]
It's in section 2.3.1 of RFC 6749:

> The authorization server MUST support the HTTP Basic authentication
scheme for authenticating clients that were issued a client password.

When integrating with various OPs/ASes, we've seen this one missed a lot.
Great that the cert tests catch it.

**Comment by selfissued** [comment]
There are two separate issues here.  It would be good to enhance the testing code so that it works for configurations that don't support client_secret_basic wherever possible.  (This is being worked on at https://github.com/rohe/oidctest/pull/123#issuecomment-450411425 .)

However, there was an explicit decision by the OpenID Connect working group years ago that certified implementations must support client_secret_basic.  This decision is part of the of the certification profile definitions.  The current version of the certification profile definitions is at http://openid.net/wordpress-content/uploads/2018/06/OpenID-Connect-Conformance-Profiles.pdf .

**Comment by zandbelt** [comment]
I am re-opening this as it seems that though this may work (?) for OPs that are configured with a Discovery document, it apparently does not work when things have been configured statically. This blocks testing of OPs that conform to the OIDC spec but don't support `client_secret_basic` as they want to run only tests and don't want/need to certify.

See: https://op.certification.openid.net:61857/test_info/OP-IDToken-C-Signature that uses a statically configured `token_endpoint_auth_methods_supported` set to `client_secret_post` but the suite still tries to use `client_secret_basic` at runtime (because of `authn_method` passed in op_args).

**Comment by sozkan** [comment]
As discussed on skype it worked when token_endpoint_auth_method was set to client_secret_post in instance configuration. So I think we can close it again?

**Comment by zandbelt** [comment]
yep, good that this solution is now recorded; having this setting automatically adopted would be an improvement though (and I believe the code actually was setup to to this...)
