### ISSUE TITLE
"Access token request with client_secret_post authentication" tests must be ignorable?

### ISSUE THREAD

**Issue by wreulicke** [openid-certification/oidctest#63]
I am trying Basic profile tests with dynamic discovery configurations.
This test suites has "Access token request with client_secret_post authentication" test.

But, the OpenId Connect spec does not indicate that client_secret_post authentication MUST support.
So, I seem to be this test is ignorable.
http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication

In other ignorable tests, message indicating ignorable displays.
But the tests does not display message indicating ignorable.
This test is ignorable?

Or, Does my discovery endpoints provide wrong information?

**Comment by zandbelt** [comment]
The OIDC certification conformance document lists this test as mandatory to implement for Providers for the Basic profile, see: http://openid.net/wordpress-content/uploads/2016/12/OpenID-Connect-Conformance-Profiles.pdf. This document is leading for the certification requirements.

The certification effort aims to maximize interoperability between arbitrary RPs and OPs and as such it may require slightly more than just the bare minimum from the spec. Since there may be RPs that are not capable of modifying the HTTP headers for Basic authentication, it to makes sense to also support a method that supports authentication through POST parameters without adding a lot of complexity.

I'll leave it up to @selfissued and @rohe to provide more color.

**Comment by selfissued** [comment]
Hans' description of the reason for this test is correct. It's there to enhance interoperability.

**Comment by wreulicke** [comment]
Thank you for your help, @zandbelt and @selfissued.

I got it.
