### ISSUE TITLE
OP-request_uri-Unsigned: request_object_signing_alg must not be null

### ISSUE THREAD

**Issue by yv13** [openid-certification/oidctest#67]
The client registration request for the **OP-request_uri-Unsigned** test is incomplete, the `request_object_signing_alg` is set to `null` whereas it should be set to a request object JWS algorithm that is advertised as supported by the OP.

```
{
"redirect_uris": ["https://op.certification.openid.net:60381/authz_cb"], 
"application_type": "web",
 "jwks_uri": "https://op.certification.openid.net:60381/static/jwks_60381.json", 
"post_logout_redirect_uris": ["https://op.certification.openid.net:60381/logout"], 
"request_object_signing_alg": null, 
"grant_types": ["authorization_code"], 
"contacts": ["roland@example.com"], 
"request_uris": ["https://op.certification.openid.net:60381/requests/d3c028cd6365e599cae284c290a3b9875ee930ee535e19c423b70b9f7c320571#KnRIIkZvUUv8zVlG
"], 
"response_types": ["code"]
}
```

**Comment by yv13** [comment]
May or may not be related to iss #38

**Comment by zandbelt** [comment]
So you are saying in this case it should explicilty be "none" since we're dealing with an unsigned `request_uri`?

**Comment by yv13** [comment]
Hi Hans,

When we last ran cert suite with success, that test was setting the JWS algorithm to "none". Which, yes, it does imply an unsigned request_uri.

**Comment by zandbelt** [comment]
@rohe : do you foresee any problems just changing:
https://github.com/openid-certification/oidctest/blob/master/test_tool/cp/test_op/flows/OP-request_uri-Unsigned.json#L17
from "null" to "none"?

**Comment by panva** [comment]
I looked into why my server implementation was ignoring `null` values in the first place, the reason is the supported RFC7592 which mentions servers MAY ignore null and empty string values. This is mentioned for the update request only and is not mentioned in OIDC Dynamic Client Registration 1.0 at all.

After fixing my provider implementation (not having it ignore null values for create) i found the same affects `OP-request-Unsigned` aswell.

`null` is also sent for `OP-request_uri-Enc`, however here i would say that either a specific alg is chosen or the property is not sent at all (is omitted) to have the * behaviors of OPs kick in.

`null` is also sent for `OP-UserInfo-Enc` and `OP-Rotation-RP-Enc` where the value should either not be sent or a supported one should be chosen.

> request_object_signing_alg
OPTIONAL. JWS [JWS] alg algorithm [JWA] that MUST be used for signing Request Objects sent to the OP. All Request Objects from this Client MUST be rejected, if not signed with this algorithm. Request Objects are described in Section 6.1 of OpenID Connect Core 1.0 [OpenID.Core]. This algorithm MUST be used both when the Request Object is passed by value (using the request parameter) and when it is passed by reference (using the request_uri parameter). Servers SHOULD support RS256. The value none MAY be used. The default, if omitted, is that any algorithm supported by the OP and the RP MAY be used.

**Comment by zandbelt** [comment]
the change for OP-request_uri-Unsigned was rolled out just now as part of OP release 2.0.10; I think we'll need to look at the others carefully; I'll add those to a new ticket

**Comment by yv13** [comment]
Thank you Hans and everyone else for resolving this!
